#!/usr/bin/env node

// a script to RUN TESTS.  You can specify WHAT TESTS to run by
// populating an environment variable 'WHAT_TESTS'.  Values include:
//   * 'back' - backend unit tests with a zero-dependency json db

const
spawn = require('child_process').spawn,
exec = require('child_process').exec,
rimraf = require('rimraf'),
path = require('path');

// WHAT TESTS are we running?
var whatTests = [];
if (!process.env['WHAT_TESTS']) {
  whatTests = [ 'all' ];
} else {
  whatTests.push(process.env['WHAT_TESTS']);
}

if (whatTests[0] == 'all') whatTests = [ 'back' ];

var ec = 0;
var frontend_test_filter = process.env['FRONTEND_TEST_FILTER'] ?
                           ' (filter: ' + process.env['FRONTEND_TEST_FILTER'] + ')' :
                           '';

function run() {
  if (!whatTests.length) {
    process.exit(ec);
  }

  var testName = whatTests.shift();

  const availConf = {
    back: {
      what: "API level unit tests using a JSON database",
      node_env: 'test_json',
      script: 'test_backend'
    }
  };
  var conf = availConf[testName];

  if (!conf) {
    console.log('I don\'t know how to run this test: "' + testName + '"');
    console.log('valid choices include:', Object.keys(availConf).join(', '));
    ec = 1;
    return run();
  }

  console.log(">>> Now Running:", conf.what);
  process.env['NODE_ENV'] = conf.node_env;
  var kid = spawn(path.join(__dirname, conf.script));
  kid.stdout.on('data', function(d) { process.stdout.write(d); });
  kid.stderr.on('data', function(d) { process.stderr.write(d); });
  kid.on('exit', function(code) {
    if (code) ec = code;
    run();
  });
}

run();
